categories = ["Added", "Changed", "Fixed", "Improved", "Removed", 'Bump', 'Release']
category_delimiters = ["[", "]"]
colored_output = true
enable_debug = true
excluded_commit_tags = ['v', "cargo-release"]
enable_footers = false
show_commit_hash = false
show_prefix = false
sort_by = "date"
template_prefix = "GH-NNNN"
